name: Build

on:
  workflow_dispatch:

jobs:
  build-binaries:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        architecture: [armv6, armv7, aarch64]

    runs-on: ${{ matrix.os }}
    name: Build binary on ${{ matrix.os }}
    steps:
      - 
        name: Check out the repo
        uses: actions/checkout@v2
      -
        name: Build binary
        run: |
          make
      -
        name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.releaseFileName }}
          path: ${{ matrix.outputFile }}

  release:
    needs: [build-binaries]
    runs-on: ubuntu-latest
    steps:
      - 
        name: Check out the repo
        uses: actions/download-artifact@v2
    