name: Release

on:
  push:
  # workflow_dispatch:
  #   inputs:
  #     version:
  #         description: The version of the project to build
  #         type: string
  #         required: true
  #         default: 'latest'

jobs:
  release:
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Setup Xmake
        uses: xmake-io/github-action-setup-xmake@v1
      # if on macos
      -
        name: MacOs Xmake config
        if: matrix.os == 'macos-latest'
        run: xmake config -y --cxflags="-Wall -Wextra -pedantic" --cxx=$(brew --prefix llvm@14)/bin/clang
      -
        name: Windows & Linux Xmake config
        if: matrix.os != 'macos-latest'
        run: xmake config -y --cxflags="-Wall -Wextra -pedantic"
      -
        name: Build
        run: xmake
