name: Release

on:
  push:
  # workflow_dispatch:
  #   inputs:
  #     version:
  #         description: The version of the project to build
  #         type: string
  #         required: true
  #         default: 'latest'

jobs:
  release:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest] # , macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3

      # if running on ubuntu, we need to install g++
      - 
        name: Install g++
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
          sudo add-apt-repository -y ppa:deadsnakes/ppa
          sudo apt -q update
          sudo apt-get install g++ gcc ninja-build
      -
        name: Setup Xmake
        uses: xmake-io/github-action-setup-xmake@v1
      -
        name: Build
        run: xmake -y