name: Release

on:
  push:
  # workflow_dispatch:
  #   inputs:
  #     version:
  #         description: The version of the project to build
  #         type: string
  #         required: true
  #         default: 'latest'

jobs:
  build-ubuntu:
    runs-on: ubuntu-22.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Setup ARM toolchains
        run: |
          wget https://releases.linaro.org/components/toolchain/binaries/latest-7/aarch64-linux-gnu/gcc-linaro-7.5.0-2019.12-x86_64_aarch64-linux-gnu.tar.xz -O /tmp/gcc-linaro-7.5.0-2019.12-x86_64_aarch64-linux-gnu.tar.xz
          tar -xf /tmp/gcc-linaro-7.5.0-2019.12-x86_64_aarch64-linux-gnu.tar.xz -C /tmp
      -
        name: Setup Xmake
        uses: xmake-io/github-action-setup-xmake@v1
      -
        name: Update Xmake to `dev` branch # because need features that aren't released yet (will be in 2.7.2)
        run: xmake update -s dev
      -
        name: Build
        run: |
          xmake -y
          # xrepo remove --all fmt -y
          xmake f -p cross -a arm64 -c -y --sdk=/tmp/gcc-linaro-7.5.0-2019.12-x86_64_aarch64-linux-gnu/
          xmake -y

  build-windows:
    runs-on: windows-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Setup Xmake
        uses: xmake-io/github-action-setup-xmake@v1
      -
        name: Update Xmake to `dev` branch # because need features that aren't released yet (will be in 2.7.2)
        run: xmake update -s dev
      -
        name: Build (Windows)
        run: |
          xmake -y

  build-macos:
    runs-on: macos-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Setup Xmake
        uses: xmake-io/github-action-setup-xmake@v1
      -
        name: Update Xmake to `dev` branch # because need features that aren't released yet (will be in 2.7.2)
        run: xmake update -s dev
      -
        name: MacOs Xmake config
        run: xmake config -y --cxx=$(brew --prefix llvm@14)/bin/clang
      -
        name: Build (MacOs)
        run: |
          xmake -y
          xmake f -a arm64
          xmake -y

  # release:
  #   needs: [build-ubuntu, build-windows, build-macos]
  #   steps:
  #     -
  #       name: Checkout
  #       uses: actions/checkout@v3
